### PR TITLE
Move towards StrictComparisons

### PR DESCRIPTION
**Pull request by szepeviktor**
`WordPress.PHP.StrictComparisons`

@joshuadavidnelson ~~There will be very sensitive changes. Could you help?~~

### CODE REVIEW

**Comment by szepeviktor** [comment]
Suprise :) 🎉 

Ready to merge 😹

**Comment by joshuadavidnelson** [comment]
Hey @szepeviktor - this doesn't seem to have any impact on the tests - I assume that's because the code already meets the strict comparisons check. Just want to be sure I'm not missing something...

**Comment by szepeviktor** [comment]
You got it right.

**Comment by joshuadavidnelson** [comment]
I'm not going to bother with a new version or release, since this is only impacts github checks

**Pull request merged**
