### PR TITLE
v0.4.9

### LINKED ISSUE #24: Add 3 basic zero-coverage tests to CI
1. syntax check
1. coding standard
1. static analysis

What do you think?

### PR DESCRIPTION
**Pull request by joshuadavidnelson**
Includes the following:
- **Notice:** Added the minimum PHP version requirement of 5.3, which was not explicitly set before now.
- **Big change:** the plugin now changes the `post_type` arguments for posts so they are no longer public and removes all post_type support parameters. This disables the post-related admin redirects, as WordPress will now show users an error page stating "Sorry, you are not allowed to edit posts in this post type." It also pulls posts out of a lot of other locations (menus, etc, achieving the same thing as #36. Thanks to @chesio for his contribution there) and is a much more efficient method of "disabling" the 'post' type. This method is also used on built-in taxonomies, unless another post type supports them. **This change may impact other plugins or themes, be sure to back up your site and, if you can, test these changes prior to updating the plugin on a production site.**
- Add basic static php tests and update code to pass those test, closes #24. Huge props to @szepeviktor.
- Disable pingbacks entirely.
- Fix comment redirect/menu functionality, now correctly removes comments and redirects `edit-comments.php` admin page if no other post type support comments (note that WordPress default is for pages and attachments to support comments).
- Fully disabling XMLRPC for posts and tags/categories. Tag/categories remain if another post type supports them.
- Initiate plugin via `plugins_loaded` hook.
- Change the admin notice related to blog and home page settings, only showing notices if no homepage is set or if the blog and homepage are the same page.
- Flush rewrite rules at activation and deactivation.
- Filtering out `post` post types from all archives, previously it was just author archives and search results.
- Removes post, category, and tag options from all menus. Tag/categories remain if another post type supports them.
- Remove header feed urls, unless supported by another post type.
- Wordpress 5.5 support:
	- Remove 'post' post type from XML sitemaps.
	- Remove built-in taxonomies from XML sitemaps, if not being used by a custom post type.
	- Fix sitemap redirect issues.
- **Developers:** Filters were removed and altered in this version:
	- The `dwpb_redirect_feeds` filter now has (3) params, to match those in the `dwpb_disable_feed` filter: $bool, $post, $is_comment_feed.
	- The `dwpb_author_post_types` filter is now `dwpb_archive_post_types`, as the query modification now includes all pages passing `is_archive`.
	- Removed filters: `dwpb_disable_rest_api`, `dwpb_remove_post_comment_support`, `dwpb_remove_post_trackback_support`, `dwpb_redirect_admin_edit_single_post`, `dwpb_redirect_single_post_edit`, `dwpb_redirect_admin_edit_post`, `dwpb_redirect_edit`, `dwpb_redirect_admin_post_new`, `dwpb_redirect_post_new` as these are rendered obsolute by above changes.

### CODE REVIEW

**Comment by joshuadavidnelson** [comment]
Hey @szepeviktor and @chesio - any chance you would be able/willing to review these changes? There is a lot of improvements here and some overlap with #36, I would be grateful for a second and/or third pair of eyes before release. Thanks again for your contributions so far!

**Comment by szepeviktor** [comment]
Hello Joshua!
I refer you to these 3 _basic_ tools: https://github.com/joshuadavidnelson/disable-blog/pull/27/files#diff-d948ac4d33809eeb8eafe9eb59a6d05a
Please merge that PR or use these 3 tools in any other way.

After that I would gladly review your code ❤️

**Comment by szepeviktor** [comment]
Please consider moving old-style _todo-in-code_ to modern GitHub Issue.

**Comment by joshuadavidnelson** [comment]
Hey Viktor! Thanks for the quick feedback. I have to move onto other things today, but my next task is to circle back to your PR. I'll try to get that integrated into this PR in the next day or two and then I'll reach out again. Thanks for the help!

**Comment by szepeviktor** [comment]
> Requires at least: 3.1.0

Does it mean that disable-blog must run on PHP 5.2?

**Comment by joshuadavidnelson** [comment]
> > Requires at least: 3.1.0
> 
> Does it mean that disable-blog must be able to run on PHP 5.2?

Hmm, I guess it could be interpreted that way based on [the core PHP compatibility](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/). I haven't updated the min WP version in some time, it was originally based on [this tool](https://wpseek.com/pluginfilecheck/), but I believe that tool only checks for WordPress functions used in the plugin to determine the minimum version.

I could update the `Requires at least` to WP 5.2 in order to drop the older versions of PHP and/or add the `Requires PHP` header to the readme.txt. My preference is provide a reasonable level of backwards compatibility, but honestly I'd rather see PHP 7.0 and greater.

**Comment by joshuadavidnelson** [comment]
Hazaah! Took a little time to get all those checks passed, aside from moving abroad this last month I've also setup a new computer - so getting vscode to replicate the checks being run in github correctly took some trail-and-error. I haven't gone back through to manually check that all the plugin functionality is working as expected, but I will over the weekend.

**Comment by joshuadavidnelson** [comment]
I went back through this and since I've updated the `post_type` arguments to make posts non-public, etc there was some functions that could be removed, also wiping out the default `supports` argument for posts - this pulls posts out of a variety of places in the admin.

**Pull request merged**
